### ISSUE TITLE
Open to contribution?

### ISSUE THREAD

**Issue by kline7** [Saas-Starter-Kit/Starter-Prisma#1]
Greetz, 

I've been looking into your Open Source SaaS Kit templates the past few days and noticed you archived the other repo I was interested in. Are you open to contributors? I'm interested in seeing documentation on how you are hosting this project within AWS fargate/RDS, etc., and would like to help you in any way I can. You can contact me at spencerk98@gmail.com if you're interested. Otherwise, if you're still open to selling this as a service, I'd be willing to pay for support in getting this deployed into AWS.

**Comment by ishandutta2007** [comment]
@kline7 I am more inclined to firestore ecosystem as opposed to aws. But using postgress narrows it to only small set of people. Are you working on a fork of it for AWS ? Ideally it should have multiple db options
