### ISSUE TITLE
Text too dark in dark mode

### ISSUE THREAD

**Issue by Roshan12here** [Saas-Starter-Kit/Starter-Prisma#7]
![Screenshot (43)](https://github.com/Saas-Starter-Kit/Saas-Kit-prisma/assets/146016164/08ced31b-024e-49c0-a9f5-156dd02d7485)
The text is gray in dark mode whereas it should be Lighter in dark mode to make it better

**Comment by iqbal125** [comment]
merged your PR, thanks for the contribution.
