### ISSUE TITLE
[Feature Request] One time payment instead of subscriptions

### ISSUE THREAD

**Issue by j0yk1ll** [Saas-Starter-Kit/Starter-Prisma#9]
It would be awesome if you could the option to use one-time payments instead of subscriptions with this starterkit.

I imagine given the starterkit is sold via one-time payment, it should be trivial for you to add it and it would open up the starterkit to a whole new type of software businesses.

**Comment by iqbal125** [comment]
@j0yk1ll This is something I thought about but subscriptions are a fundamental feature of Saas apps and this boilerplate. 

It would require basically redoing the whole project to make it work well with one time payments. 

This could be something I implement in the future however.
